


{{ config(materialized='table') }}

--===============================================--
--======== CUSTOMER DETAILS =====================--
--===============================================--
SELECT
    L.LEAD_ID AS CUSTOMER_ID
    ,L.LEAD_NAME AS CUSTOMER_NAME
    ,L.SERVICE_CITY AS SERVICE_CITY
    ,L.SERVICE_STATE AS SERVICE_STATE
    ,L.SERVICE_POSTAL_CODE AS SERVICE_POSTAL_CODE
    ,L.LONGITUDE AS LONGITUDE
    ,L.LATITUDE AS LATITUDE
    ,L.LEAD_CATEGORY AS CUSTOMER_CATEGORY
    ,MIN(CAST(I.ORD_INV_INVOICE_CREATED AS DATE)) AS CUSTOMER_START_DATE
    ,L.CAMPAIGN_ID AS CAMPAIGN_ID
    ,L.PC_ORGANIZATION_ID
FROM {{ ref('D_LEAD') }} AS L
INNER JOIN {{ order_invoice() }} AS I
    ON CAST(I.ORD_INV_INTERNAL_CUSTOMER_PARTY_ID AS FLOAT) = L.LEAD_ID
GROUP BY
    L.LEAD_ID
    ,L.LEAD_NAME
    ,L.SERVICE_CITY
    ,L.SERVICE_STATE
    ,L.SERVICE_POSTAL_CODE
    ,L.LONGITUDE
    ,L.LATITUDE
    ,L.LEAD_CATEGORY
    ,L.CAMPAIGN_ID
    ,L.PC_ORGANIZATION_ID
;
