

{{ config(materialized='table') }}

--===============================================--
--======== LEAD CONTACTS AND EXCLUDED ===========--
--===============================================--
WITH CONTACTS_LEADS AS (
    SELECT DISTINCT
        PC.PC_INTERNAL_PARTY_ID AS LEAD_ID
        ,PC.PC_NAME AS LEAD_NAME
        ,PC.PC_SERVICE_CITY AS SERVICE_CITY
        ,PC.PC_SERVICE_STATE AS SERVICE_STATE
        ,PC.PC_SERVICE_POSTAL_CODE AS SERVICE_POSTAL_CODE
        ,PT.PT_ADDRESS_1 AS SERVICE_ADDRESS_1
        ,PT.PT_ADDRESS_2 AS SERVICE_ADDRESS_2
        ,NULLIF(PC.PC_LONGITUDE, 0) AS LONGITUDE
        ,NULLIF(PC.PC_LATITUDE, 0) AS LATITUDE
        ,PC.PC_CATEGORY AS LEAD_CATEGORY
        ,PC.PC_CREATED_AT AS LEAD_DATE
        ,CAM.CAMPAIGN_ID
        ,PC.PC_ORGANIZATION_ID
    FROM {{ source('DD_DWH', 'PARTY_CONTACT') }} AS PC
    LEFT JOIN {{ party_organization() }} AS PO
        ON PO.PO_INTERNAL_PARTY_ID = PC.PC_ORGANIZATION_ID
    LEFT JOIN (
        SELECT *
        FROM {{ source('DD_DWH', 'PARTY') }}
        WHERE PT_END_DATE IS NULL
    ) AS PT
        ON PT.PT_INTERNAL_PARTY_ID = PC.PC_INTERNAL_PARTY_ID
    LEFT JOIN {{ ref('D_CAMPAIGNS') }} AS CAM
        ON CAM.CAMPAIGN = PC.PC_CAMPAIGN
        AND CAM.CHANNEL = PC.PC_CHANNEL
        AND CAM.STORE_ID = PC.PC_ORGANIZATION_ID
    WHERE {{ exclude_invalid_org('PO') }}
      AND PC.PC_END_DATE IS NULL
),

EXCL_DELETED AS (
    SELECT *
    FROM CONTACTS_LEADS AS CL
    WHERE {{ exclude_deleted_invoices('CL', 0, 'LEAD_ID') }}
)

SELECT
    CL.LEAD_ID
    ,CL.LEAD_NAME
    ,CL.SERVICE_CITY
    ,CL.SERVICE_STATE
    ,CL.SERVICE_POSTAL_CODE
    ,CL.SERVICE_ADDRESS_1
    ,CL.SERVICE_ADDRESS_2
    ,CL.LONGITUDE
    ,CL.LATITUDE
    ,CL.LEAD_CATEGORY
    ,CAST(CL.LEAD_DATE AS DATE) AS LEAD_DATE
    ,CL.CAMPAIGN_ID
    ,CL.PC_ORGANIZATION_ID
FROM CONTACTS_LEADS AS CL
;
