
{{ config(materialized='table') }}

--===============================================--
--======== SERVICES UNIONED AND DEDUPED =========--
--===============================================--
WITH ITM_SERVICES AS (
    SELECT DISTINCT
        ITM.ITM_REVENUE_CATEGORY AS SERVICE_CATEGORY
        ,ITM.ITM_NAME AS SERVICE
    FROM {{ source('DD_DWH', 'ITEM') }} AS ITM
    LEFT JOIN {{ party_organization() }} AS PO
        ON ITM.ITM_STORE_ID = PO.PO_INTERNAL_PARTY_ID
    WHERE ITM.ITM_TYPE = 0
      AND {{ exclude_invalid_org('PO') }}
      AND ITM.ITM_REVENUE_CATEGORY <> 'nan'
),

INV_SERVICES AS (
    SELECT DISTINCT
        INV.ORD_INV_REVENUE_CATEGORY AS SERVICE_CATEGORY
        ,INV.ORD_INV_SERVICE_NAME AS SERVICE
    FROM {{ source('DD_DWH', 'ORDER_INVOICE') }} AS INV
    LEFT JOIN {{ party_organization() }} AS PO
        ON INV.ORD_INV_INTERNAL_ORGANIZATION_PARTY_ID = PO.PO_INTERNAL_PARTY_ID
    WHERE {{ exclude_invalid_org('PO') }}
      AND INV.ORD_INV_REVENUE_CATEGORY <> 'nan'
),

PROP_SERVICES AS (
    SELECT DISTINCT
        PROP.CJ_REVENUE_CATEGORY AS SERVICE_CATEGORY
        ,PROP.CJ_SERVICE_NAME AS SERVICE
    FROM {{ source('DD_DWH', 'CUSTOMER_JOURNEY_PROPOSALS') }} AS PROP
    LEFT JOIN {{ party_organization() }} AS PO
        ON PROP.CJ_PROP_INTERNAL_ORGANIZATION_PARTY_ID = PO.PO_INTERNAL_PARTY_ID
    WHERE {{ exclude_invalid_org('PO') }}
      AND PROP.CJ_REVENUE_CATEGORY <> 'nan'
),

UNIONED AS (
    SELECT * FROM ITM_SERVICES
    UNION
    SELECT * FROM INV_SERVICES
    UNION
    SELECT * FROM PROP_SERVICES
),

DEDUPED AS (
    SELECT DISTINCT
        ROW_NUMBER() OVER (ORDER BY SERVICE_CATEGORY, SERVICE) AS SERVICE_ID
        ,SERVICE_CATEGORY
        ,SERVICE
    FROM UNIONED
)

SELECT *
FROM DEDUPED
;