
{{ config(materialized='table') }}

--===============================================--
--======== STORE ORGANIZATION DATA ==============--
--===============================================--
WITH ORG_WITH_OPEN_SINCE AS (
    SELECT
        PO_INTERNAL_PARTY_ID
        ,CASE
            WHEN MIN(CASE WHEN RN = 1 THEN PO_OPEN_SINCE END) = '1900-01-01'
                THEN MIN(CASE WHEN RN = 2 THEN PO_OPEN_SINCE END)
            ELSE MIN(CASE WHEN RN = 1 THEN PO_OPEN_SINCE END)
        END AS PO_OPEN_SINCE
    FROM (
        SELECT
            PO_INTERNAL_PARTY_ID
            ,PO_OPEN_SINCE
            ,DENSE_RANK() OVER (
                PARTITION BY PO_INTERNAL_PARTY_ID
                ORDER BY PO_OPEN_SINCE
            ) AS RN
        FROM {{ source('DD_DWH', 'PARTY_ORGANIZATION') }}
    ) AB
    WHERE AB.RN IN (1, 2)
    GROUP BY PO_INTERNAL_PARTY_ID
),

LATEST_DATA AS (
    SELECT
        P_ORG.PO_INTERNAL_PARTY_ID AS STORE_ID
        ,1 AS BRAND_ID
        ,P_ORG.PO_INTERNAL_NAME AS STORE_NAME
        ,P_ORG.PO_ACCOUNT_MANAGER AS ACCOUNT_MANAGER
        ,NULL AS COUNTRY
        ,P_ORG.PO_REGION AS REGION
        ,ORG_OS.PO_OPEN_SINCE AS OPEN_SINCE
        ,CASE
            WHEN PO_CANCEL_DATE IS NOT NULL AND PO_CANCEL_DATE NOT IN ('None', 'nan') THEN 'TERMINATED'
            WHEN PO_TRIAL_EXPIRATION_DATE IS NOT NULL AND PO_TRIAL_EXPIRATION_DATE NOT IN ('None', 'nan') THEN 'TERMINATED'
            WHEN PO_SUSPENDED IS NULL OR PO_SUSPENDED = 1 THEN 'TERMINATED'
            ELSE 'ACTIVE'
        END AS STATUS
    FROM {{ source('DD_DWH', 'PARTY_ORGANIZATION') }} AS P_ORG
    LEFT JOIN ORG_WITH_OPEN_SINCE AS ORG_OS
        ON P_ORG.PO_INTERNAL_PARTY_ID = ORG_OS.PO_INTERNAL_PARTY_ID
    WHERE P_ORG.PO_END_DATE IS NULL
      AND {{ exclude_invalid_org('P_ORG') }}
)

SELECT *
FROM LATEST_DATA
;
