
{{ config(materialized='table') }}

--===============================================--
--======== APPOINTMENTS FACT TABLE ==============--
--===============================================--
WITH APPOINTMENTS AS (
    SELECT
        APPT.CJ_INTERNAL_APPT_ID AS APPOINTMENT_ID
        ,APPT.CJ_APPT_CLOCK_SCHEDULED_DURATION AS SCHEDULED_DURATION
        ,APPT.CJ_APPT_CLOCK_ACTUAL_DURATION AS ACTUAL_DURATION
        ,NULLIF(APPT.CJ_APPT_CREATED_AT, '1900-01-01') AS SCHEDULE_DATE
        ,APPT.CJ_APPT_TOTAL AS TOTAL
        ,APPT.CJ_APPT_COSTS AS COSTS
        ,APPT.CJ_APPT_EXPENSES AS EXPENSES
        ,APPT.CJ_APPT_TAX_RATE AS TAX_RATE
        ,APPT.CJ_APPT_GROSS_SUBTOTAL AS GROSS_SUBTOTAL
        ,APPT.CJ_APPT_SUBTOTAL AS SUBTOTAL
        ,APPT.CJ_APPT_QUANTITY AS QUANTITY
        ,APPT.CJ_APPT_MATERIAL_COST AS MATERIALS_COST
        ,APPT.CJ_APPT_LABOR_COST AS LABOR_COST
    FROM {{ source('DD_DWH', 'CUSTOMER_JOURNEY_APPOINTMENTS') }} AS APPT
    LEFT JOIN {{ party_organization() }} AS PO
        ON APPT.CJ_APPT_INTERNAL_ORGANIZATION_PARTY_ID = PO.PO_INTERNAL_PARTY_ID
    WHERE APPT.CJ_INTERNAL_APPT_ID IS NOT NULL
      AND APPT.CJ_APPT_END_DATE IS NULL
      AND {{ exclude_invalid_org('PO') }}
),

EXCL_DELETED AS (
    SELECT *
    FROM APPOINTMENTS AS A
    WHERE {{ exclude_deleted_invoices('A', 1, 'APPOINTMENT_ID') }}
)

SELECT *
FROM EXCL_DELETED
;

