version: 2

models:
  - name: D_INVOICE_STATUS
    description: "Tracks the current status of invoices with validity constraints."
    columns:
      - name: INVOICE_ID
        description: "Unique internal invoice identifier"
        tests: [not_null]
      - name: STATUS
        description: "Current invoice status"
      - name: START_DATE
        description: "Date when this status became effective"
      - name: END_DATE
        description: "Date when this status ended (null if active)"

  - name: F_INVOICE
    description: "Fact table containing invoice-level financials."
    columns:
      - name: INVOICE_ID
        description: "Unique internal invoice identifier"
        tests: [not_null, unique]
      - name: CREATE_DATE
        description: "Invoice creation timestamp"
      - name: INVOICE_DATE
        description: "Invoice issue date"
      - name: TOTAL
        description: "Total invoice amount"
      - name: BALANCE_DUE
        description: "Outstanding balance"
      - name: SUBTOTAL
        description: "Invoice subtotal before tax"
      - name: TAX_TOTAL
        description: "Total tax applied"
      - name: QUANTITY
        description: "Quantity of items/services in the invoice"
      - name: GROSS_SUBTOTAL
        description: "Subtotal before any discounts"

  - name: D_SERVICES
    description: "List of unique services across items, invoices, and proposals."
    columns:
      - name: service_id
        description: "Unique surrogate key for each service."
        tests: [unique, not_null]
      - name: service_category
        description: "Revenue category of the service."
        tests: [not_null]
      - name: service
        description: "Name of the service."
        tests: [not_null]

  - name: D_INVOICE
    description: "Invoice dimension table enriched with store, proposal, customer, service, and team member details."
    columns:
      - name: invoice_id
        description: "Unique identifier of the invoice."
        tests: [unique, not_null]
      - name: store_id
        description: "Store associated with the invoice."
      - name: proposal_id
        description: "Proposal linked to the invoice, defaults to invoice_id if no proposal exists."
      - name: lead_id
        description: "Customer or lead linked to the invoice."
      - name: invoice_type
        description: "Type/category of the invoice."
      - name: campaign_id
        description: "Campaign ID (currently null, reserved for future enrichment)."
      - name: service_id
        description: "Service linked to the invoice from d_services."
      - name: team_member
        description: "Owner/team member responsible for the invoice."

  - name: D_LEAD
    description: "Leads dimension table containing customer lead information enriched with campaign and appointment data."
    columns:
      - name: LEAD_ID
        description: "Unique identifier for the lead."
        tests: [unique, not_null]
      - name: LEAD_NAME
        description: "Name of the lead."
      - name: SERVICE_CITY
        description: "City where service is requested."
      - name: SERVICE_STATE
        description: "State where service is requested."
      - name: SERVICE_POSTAL_CODE
        description: "Postal code of service location."
      - name: SERVICE_ADDRESS_1
        description: "Primary service address."
      - name: SERVICE_ADDRESS_2
        description: "Secondary service address."
      - name: LONGITUDE
        description: "Longitude of service location."
      - name: LATITUDE
        description: "Latitude of service location."
      - name: LEAD_CATEGORY
        description: "Category of the lead."
      - name: LEAD_DATE
        description: "Effective lead date considering appointments."
        tests: [not_null]
      - name: CAMPAIGN_ID
        description: "Linked campaign identifier."
        tests:
          - relationships:
              to: ref('d_campaigns')
              field: CAMPAIGN_ID
      - name: PC_ORGANIZATION_ID
        description: "Organization ID linked to the lead."

  - name: STORE_FORECAST
    description: "Monthly store-level forecast targets compared with actual invoice performance."
    columns:
      - name: STORE_ID
        description: "Unique identifier of the store."
        tests: [not_null]
      - name: FORECAST_YEAR
        description: "Forecasted year."
        tests: [not_null]
      - name: FORECAST_MONTH
        description: "Forecasted month number (1–12)."
        tests: [not_null]
      - name: FORECAST_DATE
        description: "First day of the forecasted month."
      - name: FORECAST_TARGET
        description: "Target forecast value set for the store and month."
      - name: SUBTOTAL
        description: "Total invoice subtotal amount for the store and month."
      - name: INVOICE_BALANCE_DUE
        description: "Total remaining balance due on invoices for the store and month."

  - name: D_APPOINTMENTS
    description: "Appointment dimension linking stores, invoices, leads, proposals, and services."
    columns:
      - name: appointment_id
        description: "Unique ID for each appointment."
        tests: [unique, not_null]
      - name: store_id
        description: "Store linked to the appointment."
        tests: [not_null]
      - name: invoice_id
        description: "Invoice linked to the appointment."
      - name: proposal_id
        description: "Proposal linked to the appointment."
      - name: lead_id
        description: "Lead (customer) linked to the appointment."
      - name: campaign_id
        description: "Marketing campaign (currently null placeholder)."
      - name: service_id
        description: "Service associated with the proposal."
      - name: service_agent_id
        description: "Agent responsible for the service."
      - name: appointment_type
        description: "Type of appointment (recurring, single, etc.)."
