sources:
  - name: DD_DWH
    database: DWH
    schema: DD_DWH
    tables:
      - name: ORDER_INVOICE
      - name: PARTY_ORGANIZATION
      - name: CAMPAIGN
      - name: CUSTOMER_JOURNEY_PROPOSALS
      - name: ITEM
      - name: PARTY
      - name: PARTY_CONTACT
      - name: FORECAST
      - name: CUSTOMER_JOURNEY_APPOINTMENTS
  - name: PROD_BK
    database: DWH
    schema: PROD_BK
    tables:
      - name: SM_DELETION_EVENTS
  - name: DD_SL
    database: DWH
    schema: DD_SL
    tables:
      - name: D_SERVICES