{{ config(materialized='table') }}

WITH FORECAST AS (
    SELECT
        FOR_INTERNAL_PARTY_ID AS STORE_ID
        ,FOR_YEAR AS FORECAST_YEAR
        ,FOR_MONTH AS FORECAST_MONTH
        ,DATEFROMPARTS(FOR_YEAR, FOR_MONTH, 1) AS FORECAST_DATE
        ,FOR_TARGET AS FORECAST_TARGET
    FROM {{ source('DD_DWH', 'FORECAST') }}
    WHERE FOR_END_DATE IS NULL
),
INVOICE_SUMMARY AS (
    SELECT
        D.STORE_ID
        ,YEAR(F.INVOICE_DATE) AS INVOICE_YEAR
        ,MONTH(F.INVOICE_DATE) AS INVOICE_MONTH
        ,SUM(F.SUBTOTAL) AS SUBTOTAL
        ,SUM(F.BALANCE_DUE) AS BALANCE_DUE
    FROM {{ ref('D_INVOICE') }} AS D
    INNER JOIN {{ ref('F_INVOICE') }} AS F
        ON F.INVOICE_ID = D.INVOICE_ID
    GROUP BY D.STORE_ID, YEAR(F.INVOICE_DATE), MONTH(F.INVOICE_DATE)
)
SELECT
    F.STORE_ID
    ,F.FORECAST_YEAR
    ,F.FORECAST_MONTH
    ,F.FORECAST_DATE
    ,F.FORECAST_TARGET
    ,SUM(ISNULL(I.SUBTOTAL, 0)) AS SUBTOTAL
    ,SUM(ISNULL(I.BALANCE_DUE, 0)) AS INVOICE_BALANCE_DUE
FROM FORECAST AS F
LEFT JOIN INVOICE_SUMMARY AS I
    ON F.STORE_ID = I.STORE_ID
    AND F.FORECAST_YEAR = I.INVOICE_YEAR
    AND F.FORECAST_MONTH = I.INVOICE_MONTH
GROUP BY
    F.STORE_ID
    ,F.FORECAST_YEAR
    ,F.FORECAST_MONTH
    ,F.FORECAST_DATE
    ,F.FORECAST_TARGET
;
