name: Run dbt Tests (Azure Synapse)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-tests:
    name: Run dbt tests only
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Install Microsoft ODBC Driver 18 for SQL Server
      - name: Install ODBC Driver 18 for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      # 4️⃣ Install dbt (SQL Server adapter)
      - name: Install dbt
        run: |
          pip install dbt-core dbt-sqlserver
          dbt --version

      # 5️⃣ Configure dbt profile using GitHub Secrets
      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
dbt_testing_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: "${{ secrets.SYNAPSE_SERVER }}"
      database: "${{ secrets.SYNAPSE_DATABASE }}"
      schema: "${{ secrets.SYNAPSE_SCHEMA }}"
      user: "${{ secrets.SYNAPSE_USER }}"
      password: "${{ secrets.SYNAPSE_PASSWORD }}"
      port: 1433
      encrypt: true
      trust_cert: true
EOL


      # 6️⃣ Debug connection & run dbt tests
      - name: Run dbt tests
        run: |
          dbt debug --target dev
          dbt test --target dev
